[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "budgie"
version = "0.0.1"
description = "Budgie, a budget application for normies"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "PyQt6",
    "odswriter",
]

[project.scripts]
budgie = "main:main"

[tool.setuptools]
py-modules = ["main"]
